// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmyqsmbsjcnvmdxxwlkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5teXFzbWJzamNudm1keHh3bGtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMzEyNzMsImV4cCI6MjA2NzYwNzI3M30.gZOWif5xuu8D5-FfvlLSs459oqS39kL9ypD0l4sGamA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});